//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal_sqlce.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class egzEntities : DbContext
    {
        public egzEntities()
            : base("name=egzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orgs> Orgs { get; set; }
        public virtual DbSet<r_abp> r_abp { get; set; }
        public virtual DbSet<r_bud_type> r_bud_type { get; set; }
        public virtual DbSet<r_enstru> r_enstru { get; set; }
        public virtual DbSet<r_fsource> r_fsource { get; set; }
        public virtual DbSet<r_months> r_months { get; set; }
        public virtual DbSet<r_point_types> r_point_types { get; set; }
        public virtual DbSet<r_prg> r_prg { get; set; }
        public virtual DbSet<r_specific> r_specific { get; set; }
        public virtual DbSet<r_sprg> r_sprg { get; set; }
        public virtual DbSet<r_subj_type> r_subj_type { get; set; }
        public virtual DbSet<r_trade_method> r_trade_method { get; set; }
        public virtual DbSet<r_trade_method_just> r_trade_method_just { get; set; }
        public virtual DbSet<ref_kato> ref_kato { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
    }
}
