//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal_sqlce.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_prg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public r_prg()
        {
            this.r_sprg = new HashSet<r_sprg>();
            this.UserData = new HashSet<UserData>();
        }
    
        public long id { get; set; }
        public string code { get; set; }
        public string name_kz { get; set; }
        public string name_ru { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<long> abp { get; set; }
    
        public virtual r_abp r_abp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<r_sprg> r_sprg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserData> UserData { get; set; }
    }
}
