//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal_sqlce.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_kato
    {
        public long code { get; set; }
        public string name_kz { get; set; }
        public string name_ru { get; set; }
        public string full_name_kz { get; set; }
        public string full_name_ru { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
    }
}
