//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal_sqlce.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public long Id { get; set; }
        public Nullable<long> abp { get; set; }
        public Nullable<long> stru { get; set; }
        public Nullable<long> monthId { get; set; }
        public long Year { get; set; }
        public string Deliver_kz { get; set; }
        public string Deliver_ru { get; set; }
        public string Description_kz { get; set; }
        public string Description_ru { get; set; }
        public Nullable<long> DisablePerson { get; set; }
        public string SubjectTypeCode { get; set; }
        public string ExtraDescription_kz { get; set; }
        public string ExtraDescription_ru { get; set; }
        public Nullable<long> FinSource { get; set; }
        public string mkeiId { get; set; }
        public int Count { get; set; }
        public decimal price { get; set; }
        public decimal YearSum1 { get; set; }
        public decimal YearSum2 { get; set; }
        public decimal YearSum3 { get; set; }
        public decimal Prepayment { get; set; }
        public long kato { get; set; }
        public string supplyDateKz { get; set; }
        public string supplyDateRu { get; set; }
        public Nullable<long> TradeMethod { get; set; }
        public Nullable<long> tradeMethodJust { get; set; }
        public Nullable<long> Program { get; set; }
        public Nullable<long> SubProgram { get; set; }
        public Nullable<long> Specific { get; set; }
        public Nullable<long> pointTypeCode { get; set; }
        public Nullable<decimal> Summ { get; set; }
    
        public virtual r_abp r_abp { get; set; }
        public virtual r_enstru r_enstru { get; set; }
        public virtual r_fsource r_fsource { get; set; }
        public virtual r_months r_months { get; set; }
        public virtual r_point_types r_point_types { get; set; }
        public virtual r_prg r_prg { get; set; }
        public virtual r_specific r_specific { get; set; }
        public virtual r_sprg r_sprg { get; set; }
        public virtual r_subj_type r_subj_type { get; set; }
        public virtual r_trade_method r_trade_method { get; set; }
        public virtual r_trade_method_just r_trade_method_just { get; set; }
    }
}
